apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "nish-29-jan-test-5"
  description: "This is a sample gRPC SpringBoot App to showcase Scaffolder in Backstage"
  annotations:
    github.com/project-slug: NishkarshRaj/nish-29-jan-test-5
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/seo"